import type { Metadata } from 'next';
import './globals.css';
import { DM_Sans } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { SessionProvider } from 'next-auth/react';
import StickyTop from '@/components/navbar/StickyTop';
import Footer from '@/components/footer/Footer';
import FactoriesProvider from '@/lib/FactoriesProvider';
import { auth } from '../../auth';
const dm_sans = DM_Sans({ subsets: ['latin'], variable: '--font-dm-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log(session, 'seslay');

  return (
    <html lang='en'>
      <body className={`${dm_sans.className} antialiased`}>
        <SessionProvider session={session}>
          <FactoriesProvider propsData={session}>
            {' '}
            <StickyTop />
            {children}
            <Toaster />
            <Footer />
          </FactoriesProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
